# Generated by Django 4.0.6 on 2022-08-25 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_long', models.CharField(max_length=50)),
                ('color_short', models.CharField(max_length=5)),
                ('color_esk', models.CharField(max_length=5)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['color_long'],
            },
        ),
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('number', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('F', 'samica'), ('M', 'samiec')], max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('L', 'loty'), ('R', 'rozpłód'), ('A', 'archiwum'), ('M', 'martwy')], max_length=1, null=True)),
                ('image_body', models.ImageField(blank=True, null=True, upload_to='pigeons/body')),
                ('image_wing', models.ImageField(blank=True, null=True, upload_to='pigeons/wing')),
                ('image_eye', models.ImageField(blank=True, null=True, upload_to='pigeons/eye')),
                ('death_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pigeons.color')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfFather', to='pigeons.pigeon')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfMother', to='pigeons.pigeon')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
